### ISSUE TITLE
Update !

### ISSUE THREAD

**Issue by OctaEDLP00** [Zerthick/CommandBooks#3] opened 2020-09-05 22:28 UTC
update for **sponge** forge 1.12.2 2838 **7.3.0**

**Comment by Zerthick** [comment] 2020-12-02 03:41
See if this version works: https://github.com/Zerthick/CommandBooks/releases/tag/v1.6.1 :smiley:

**Comment by Zerthick** [comment] 2020-12-09 22:44
Closing as duplicate of #2

**Closed as completed by Zerthick** 2020-12-09 22:44 UTC
